---
- name: PostgreSQL | Add PostgreSQL repository | RHEL
  yum_repository:
    name: postgresql
      description: postgresql yum repo
      baseurl: "{{ postgresql_yum_repository_baseurl }}"
      gpgkey: "{{ postgresql_yum_repository_gpgkey }}"
      enabled: yes
    when: postgresql_install_repository