---
dependency:
  name: galaxy
  options:
    role-file: molecule/postgres_hardening/requirements.yml
    requirements-file: molecule/postgres_hardening/requirements.yml
driver:
  name: docker
lint: |
  yamllint roles/postgres_hardening/ molecule/postgres_hardening/ .github/workflows/postgres_hardening.yml
  ansible-lint roles/postgres_hardening/
platforms:
  - name: instance
    image: "rndmh3ro/docker-${MOLECULE_DISTRO}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    tty: true
    env:
      container: docker
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # not idempotent
    - verify
    - destroy
